<a href="https://colab.research.google.com/github/diki123456/apiuser/blob/master/Salinan_dari_Answer_Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Buatlah variabel dengan nama ClubEropa dengan tipe data dictionary 4 key (nama_club, 
pelatih_club, Negara, pelatih), yang masing-masing nya memiliki 4 value

In [ ]:
#1
club_eropa = {
    "nama_club":["fcb","lvc","cfc","persija"],
    "pelatih_club":["rv","kl","mj","jono"],
    "negara":["ind","mly","aus","jpn"],
    "pelatih":["pp","jk","op","kl"]
    }

print(club_eropa)

{'nama_club': ['fcb', 'lvc', 'cfc', 'persija'], 'pelatih_club': ['rv', 'kl', 'mj', 'jono'], 'negara': ['ind', 'mly', 'aus', 'jpn'], 'pelatih': ['pp', 'jk', 'op', 'kl']}


Tambahkan key sponsor pada variabel ClubEropa yang tentunya memiliki 4 value

In [ ]:
#2 
sponsor = {"sponsor":["ol","tok","lh","gh"]}
club_eropa.update(sponsor)
print(club_eropa)


{'nama_club': ['fcb', 'lvc', 'cfc', 'persija'], 'pelatih_club': ['rv', 'kl', 'mj', 'jono'], 'negara': ['ind', 'mly', 'aus', 'jpn'], 'pelatih': ['pp', 'jk', 'op', 'kl'], 'sponsor': ['ol', 'tok', 'lh', 'gh']}


 Buatlah 4 variable array yang memiliki 5 elemen angka pada masing-masing nya (bebas nama 
array dan elemennya), kemudian lakukan:
a. Perkalian pada variable array 1 dengan variable array 3
b. Penjumlahan pada variable array 2 dengan variable array 4
b. Jika ada irisan, dapatkan irisan pada variable 1 dengan 4
c. Ambil nilai pada urutan ke 1, 3, dan 5 pada variabel kedu

In [ ]:
#3
import numpy as np
a = np.array([2,3,4,5,6])
b = np.array([4,5,6,7,8])
c = np.array([1,0,7,9,5])
d = np.array([2,4,5,6,7])

print(a * c)
print(b + d)
print(np.intersect1d(a,d))
print(b[[0, 2, 4]])

[ 2  0 28 45 30]
[ 6  9 11 13 15]
[2 4 5 6]
[4 6 8]


Buatlah variabel nilai_kelas dari 4 kelas berbeda, dimana
masing-masing kelas berisi nilai 4 siswa, kemudian kurangi semua
nilai siswa dengan 5 sebagai nilai hukuman karena menyontek

In [ ]:
#4
nilai_kelas = np.array([[20,30,40,50], 
                        [40,30,60,100],
                        [50,60,70,90],
                        [60,50,90,50]])

hukuman = nilai_kelas - 5
print(hukuman)

[[15 25 35 45]
 [35 25 55 95]
 [45 55 65 85]
 [55 45 85 45]]
